/*
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

package com.pingidentity.device.id

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.math.BigInteger
import java.security.Key
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.SecureRandom
import javax.security.auth.x500.X500Principal

/**
 * Utility class for managing cryptographic keys in the Android KeyStore.
 *
 * This class provides functionality to:
 * - Generate and retrieve RSA key pairs
 * - Check for the existence of keys
 * - Remove keys from the KeyStore
 *
 * The keys generated by this manager:
 * - Use 2048-bit RSA key pairs
 * - Are stored in the system's hardware-backed KeyStore when available
 * - Persist across app restarts
 */
internal object KeyManager {

    /** The name of the Android KeyStore provider */
    private const val ANDROID_KEYSTORE: String = "AndroidKeyStore"

    /** The Common Name used in the certificate's Distinguished Name */
    private const val CN_PING_IDENTITY = "CN=PINGIDENTITY"

    /** The size in bits of the RSA key to generate */
    private const val KEY_SIZE = 2048

    /**
     * Returns a public key for the specified alias.
     * If a key with the given alias doesn't exist, a new key pair is generated.
     *
     * @param alias The alias under which the key is stored in the KeyStore
     * @return The public key corresponding to the alias
     */
    internal fun identifierKey(alias: String): Key {
        val keyStore = this.keyStore
        return if (!containsKey(alias)) {
            KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_RSA, ANDROID_KEYSTORE).apply {
                initialize(getSpec(alias))
            }.generateKeyPair().public
        } else {
            keyStore.getCertificate(alias).publicKey
        }
    }

    /**
     * Checks if a key with the specified alias exists in the KeyStore.
     *
     * @param alias The alias to check
     * @return true if the key exists, false otherwise
     */
    internal fun containsKey(alias: String): Boolean {
        return keyStore.containsAlias(alias)
    }

    /**
     * Removes a key with the specified alias from the KeyStore.
     *
     * @param alias The alias of the key to remove
     */
    internal fun removeKey(alias: String) {
        keyStore.deleteEntry(alias)
    }

    /**
     * Gets a reference to the Android KeyStore and initializes it.
     *
     * @return An initialized KeyStore instance
     */
    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(ANDROID_KEYSTORE).apply {
            load(null)
        }
    }

    /**
     * Creates key generation parameters for the specified alias.
     *
     * @param alias The alias for which to create the specification
     * @return A KeyGenParameterSpec configured for RSA key generation
     */
    private fun getSpec(alias: String): KeyGenParameterSpec {
        return KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
        )
            .setKeySize(KEY_SIZE)
            .setCertificateSubject(X500Principal(CN_PING_IDENTITY))
            .setCertificateSerialNumber(BigInteger(16, SecureRandom()))
            .setDigests(KeyProperties.DIGEST_SHA256)
            .setSignaturePaddings(KeyProperties.SIGNATURE_PADDING_RSA_PKCS1)
            .build()
    }
}