/*
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

package com.pingidentity.device.root.detector

import android.os.Build

/**
 * Release-Keys and Test-Keys has to do with how the kernel is signed when it is compiled.
 * Test-Keys means it was signed with a custom key generated by a third-party developer.
 */
private const val TEST_KEYS = "test-keys"

val BuildTagsDetector by lazy {
    RootDetector {
        if (Build.TAGS != null && Build.TAGS.contains(TEST_KEYS)) {
            1.0
        } else {
            0.0
        }
    }
}