package com.pingidentity.device.profile.detector

import android.content.Context
import android.os.Build
import com.pingidentity.device.root.BaseRootDetector

/**
 * Release-Keys and Test-Keys has to do with how the kernel is signed when it is compiled.
 * Test-Keys means it was signed with a custom key generated by a third-party developer.
 */
class BuildTagsDetector : RootDetector<BaseRootDetector> {

    override val key: String
        get() = BuildTagsDetector::class.java.simpleName

    override fun isRooted(context: Context): Double {
        return if (Build.TAGS != null && Build.TAGS.contains(TEST_KEYS)) {
            1.0
        } else {
            0.0
        }
    }

    companion object {
        private const val TEST_KEYS = "test-keys"
    }
}