#
# Copyright (c) 2024. PingIdentity. All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

name: Run integration tests on emulators
on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      testrail-run-id:
        description: TestRail Run ID
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: Slack Notifier Incoming Webhook
        required: true
      TESTRAIL_USERNAME:
        description: TestRail username
        required: true
      TESTRAIL_API_KEY:
        description: TestRail API key
        required: true
jobs:
  integration-tests:
    runs-on: ${{ inputs.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        api-level: [29]

    steps:
      # Clone the repo
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      # Setup JDK and cache and restore dependencies.
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Enable KVM for the emulators
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # Update the testrail integration configuration (this is a hack...)
      - name: Update the testrail integration configuration
        run: |
          cat foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt
          sed -i -e "s/\"TESTRAIL_ENABLE\", \".*\"/\"TESTRAIL_ENABLE\", \"${{vars.TESTRAIL_ENABLE}}\"/g" foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt
          sed -i -e "s/\"TESTRAIL_DEBUG\", \".*\"/\"TESTRAIL_DEBUG\", \"${{vars.TESTRAIL_DEBUG}}\"/g" foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt
          sed -i -e "s/\"TESTRAIL_PROJECT_ID\", \".*\"/\"TESTRAIL_PROJECT_ID\", \"${{vars.TESTRAIL_PROJECT_ID}}\"/g" foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt
          sed -i -e "s/\"TESTRAIL_RUN_ID\", \".*\"/\"TESTRAIL_RUN_ID\", \"${{inputs.testrail-run-id}}\"/g" foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt
          sed -i -e "s/\"TESTRAIL_USERNAME\", \".*\"/\"TESTRAIL_USERNAME\", \"${{secrets.TESTRAIL_USERNAME}}\"/g" foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt
          sed -i -e "s/\"TESTRAIL_API_KEY\", \".*\"/\"TESTRAIL_API_KEY\", \"${{secrets.TESTRAIL_API_KEY}}\"/g" foundation/testrail/src/main/kotlin/com/pingidentity/testrail/TestRailClientConfig.kt

      # Execute all integration tests
      - name: Execute integration tests
        env:
          # These environment variables don't work with the emulator-runner action for some reason
          TESTRAIL_ENABLE: ${{vars.TESTRAIL_ENABLE}}
          TESTRAIL_DEBUG: ${{vars.TESTRAIL_DEBUG}}
          TESTRAIL_URL: ${{vars.TESTRAIL_URL}}
          TESTRAIL_PROJECT_ID: ${{vars.TESTRAIL_PROJECT_ID}}
          TESTRAIL_RUN_ID: ${{inputs.testrail-run-id}}
          TESTRAIL_USERNAME: ${{secrets.TESTRAIL_USERNAME}}
          TESTRAIL_API_KEY: ${{secrets.TESTRAIL_API_KEY}}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew --rerun-tasks connectedCheck

      # Publish test reports for the unit tests
      - name: Publish test results
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Integration tests results - API Level ${{ matrix.api-level }}
          path: '**/build/outputs/androidTest-results/**/TEST-*.xml'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          reporter: java-junit